FROM node:10

COPY certificados/CompassoFW.pem /usr/CompassoFW.pem
ENV NODE_EXTRA_CA_CERTS=/usr/CompassoFW.pem

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY package*.json ./
RUN npm install

COPY . .
COPY --chown=node:node . .
USER node

EXPOSE 3000

CMD [ "node", "index.js" ]